### ISSUE TITLE
Bilara public launch roadmap

### ISSUE THREAD

**Issue by sujato** [suttacentral/bilara#55]
Here is a list of items to be checked before considering Bilara ready for general use.

- [x] Search UI: search and replace. #11 
- [x] Implement basic publication model (see bilara-data README). A more sophisticated version for the future:  https://github.com/suttacentral/suttacentral/issues/1589
- [x] Implement permissions model. #54
- [x] Fix submit TM match on hover bug #31 
- [x] Fix bug stopping undo on TM submission #26 
- [x] Ensure page load error is fixed: #56
